# Generated by Django 4.2.17 on 2025-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enamad', models.CharField(blank=True, max_length=1000, null=True)),
                ('telegram', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='media/logo/')),
                ('favicon', models.ImageField(upload_to='media/favicon/')),
                ('about_us', models.TextField(blank=True, null=True)),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='media/about_us_image/')),
                ('telegram_bot', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_us', models.TextField(blank=True, null=True)),
                ('contact_us_image', models.ImageField(blank=True, null=True, upload_to='media/contact_us_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/sliders/')),
                ('link', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
