# Generated by Django 4.2.17 on 2025-01-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='SiteSettings',
        ),
    ]
