# Generated by Django 5.1.6 on 2025-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='goftino_id',
            field=models.CharField(blank=True, help_text='شناسه گفتینو رو اینجا وارد کنید (مثل 1234567890)', max_length=20, null=True, verbose_name='شناسه گفتینو'),
        ),
    ]
