# Generated by Django 5.1.6 on 2025-03-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام برند')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/brand/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('meta_title', models.CharField(max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(verbose_name='توضیحات متا')),
                ('meta_keywords', models.TextField(verbose_name='کلمات کلیدی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/category/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('meta_title', models.CharField(max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(verbose_name='توضیحات متا')),
                ('meta_keywords', models.TextField(verbose_name='کلمات کلیدی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام رنگ')),
                ('code', models.CharField(max_length=200, verbose_name='کد رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سایز')),
                ('code', models.CharField(max_length=200, verbose_name='کد سایز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='تصویر')),
                ('meta_title', models.CharField(max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(verbose_name='توضیحات متا')),
                ('meta_keywords', models.TextField(verbose_name='کلمات کلیدی')),
                ('count_view', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('count_sell', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('real_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت واقعی')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product_images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('real_price', models.IntegerField(verbose_name='قیمت واقعی')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'تنوع',
                'verbose_name_plural': 'تنوع\u200cها',
            },
        ),
    ]
