# Generated by Django 5.1.6 on 2025-03-01 14:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ')),
                ('meta_title', models.CharField(max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(verbose_name='توضیحات متا')),
                ('meta_keywords', models.TextField(verbose_name='کلمات کلیدی')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
            },
        ),
    ]
