# Generated by Django 4.2.17 on 2025-01-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
    ]
