# Generated by Django 4.2.17 on 2025-01-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_basket_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='guest_user',
        ),
    ]
